import type { DeviceCodeInfo, DeviceFlowStatus, GitHubSession, StorageService } from "../../src/platform/services";
import type { PlatformResult } from "../../src/platform/result";
import { SessionGitHubService } from "../../src/platform/sessionGitHubService";
import { GITHUB_ACCESS_TOKEN_KEY, GITHUB_REVOKED_SESSION_KEY } from "./browserStorage";

const DEVICE_URL = "https://github.com/login/device/code";
const TOKEN_URL = "https://github.com/login/oauth/access_token";
const FORM_HEADERS = { Accept: "application/json", "Content-Type": "application/x-www-form-urlencoded" };
type Dependencies = { clientId?: string; storage: Pick<StorageService, "get" | "set" | "remove">; fetch?: typeof fetch; sleep?: (milliseconds: number, signal: AbortSignal) => Promise<void>; now?: () => number };
const cancelled = (): PlatformResult<never> => ({ ok: false, code: "cancelled", message: "Authentication cancelled" });
const expired = (): PlatformResult<never> => ({ ok: false, code: "authentication", message: "Device code expired" });
const form = (values: Record<string, string>) => new URLSearchParams(values).toString();
const object = (value: unknown): value is Record<string, unknown> => typeof value === "object" && value !== null;
function abortableSleep(milliseconds: number, signal: AbortSignal): Promise<void> { if (signal.aborted) return Promise.reject(new DOMException("Aborted", "AbortError")); return new Promise((resolve, reject) => { const timer = setTimeout(done, milliseconds); function done() { signal.removeEventListener("abort", abort); resolve(); } function abort() { clearTimeout(timer); signal.removeEventListener("abort", abort); reject(new DOMException("Aborted", "AbortError")); } signal.addEventListener("abort", abort, { once: true }); }); }

export class BrowserGitHubService extends SessionGitHubService {
  readonly availability = "available" as const;
  readonly configured: boolean;
  private readonly clientId: string;
  private readonly storage: Dependencies["storage"];
  private readonly sleeper: NonNullable<Dependencies["sleep"]>;
  private revision = 0;
  private flow = 0;
  private tokenWriteQueue: Promise<void> = Promise.resolve();
  constructor(dependencies: Dependencies) { super(dependencies.fetch ?? globalThis.fetch.bind(globalThis), dependencies.now ?? Date.now); this.clientId = dependencies.clientId?.trim() ?? ""; this.configured = !!this.clientId; this.storage = dependencies.storage; this.sleeper = dependencies.sleep ?? abortableSleep; }
  async restore(): Promise<PlatformResult<GitHubSession | null>> { const revision = this.revision; const revoked = await this.storage.get<boolean>(GITHUB_REVOKED_SESSION_KEY); if (!revoked.ok) return revoked; if (revoked.value) { return this.queueTokenOperation(async () => { if (revision !== this.revision) return cancelled(); const removed = await this.storage.remove(GITHUB_ACCESS_TOKEN_KEY); if (revision !== this.revision) return cancelled(); if (removed.ok) await this.storage.remove(GITHUB_REVOKED_SESSION_KEY); if (revision !== this.revision) return cancelled(); this.setToken(null); this.update(null); return { ok: true, value: null }; }); } const token = await this.storage.get<string>(GITHUB_ACCESS_TOKEN_KEY); if (!token.ok) return token; if (revision !== this.revision) return { ok: true, value: this.session }; this.setToken(token.value ?? null); const session = token.value ? { authenticated: true as const, login: "GitHub" } : null; this.update(session); return { ok: true, value: session }; }
  async login(): Promise<PlatformResult<GitHubSession>> { return { ok: false, code: "authentication", message: this.configured ? "Use Device Flow" : "GitHub client ID is not configured" }; }
  async startDeviceFlow(signal: AbortSignal): Promise<PlatformResult<DeviceCodeInfo>> { if (!this.configured) return { ok: false, code: "authentication", message: "GitHub client ID is not configured" }; if (signal.aborted) return cancelled(); const parsed = await this.oauthRequest(DEVICE_URL, form({ client_id: this.clientId, scope: "gist" }), signal); if (!parsed.ok) return parsed; const value = parsed.value; if (!object(value) || typeof value.device_code !== "string" || typeof value.user_code !== "string" || typeof value.verification_uri !== "string" || typeof value.expires_in !== "number" || typeof value.interval !== "number") return { ok: false, code: "invalid-data", message: "Invalid GitHub device code response" }; return { ok: true, value: value as unknown as DeviceCodeInfo }; }
  async pollDeviceFlow(info: DeviceCodeInfo, onStatus: (status: DeviceFlowStatus) => void, signal: AbortSignal): Promise<PlatformResult<GitHubSession>> {
    if (!this.configured) return { ok: false, code: "authentication", message: "GitHub client ID is not configured" }; const identity = ++this.flow; const deadline = this.now() + info.expires_in * 1000; let interval = Math.max(1, info.interval) * 1000;
    while (true) { if (signal.aborted || identity !== this.flow) return cancelled(); if (this.now() >= deadline) return expired(); try { await this.sleeper(interval, signal); } catch { return cancelled(); } if (signal.aborted || identity !== this.flow) return cancelled(); if (this.now() >= deadline) return expired(); const result = await this.oauthRequest(TOKEN_URL, form({ client_id: this.clientId, device_code: info.device_code, grant_type: "urn:ietf:params:oauth:grant-type:device_code" }), signal); if (!result.ok) return result; const body = result.value; if (!object(body)) return { ok: false, code: "invalid-data", message: "Invalid GitHub token response" }; if (body.error === "authorization_pending") { onStatus("authorization-pending"); continue; } if (body.error === "slow_down") { interval += 5000; onStatus("slow-down"); continue; } if (body.error === "access_denied") return { ok: false, code: "authentication", message: String(body.error_description ?? "Access denied") }; if (body.error === "expired_token") return expired(); if (typeof body.error === "string") return { ok: false, code: "authentication", message: String(body.error_description ?? body.error) }; if (typeof body.access_token !== "string" || body.token_type?.toString().toLowerCase() !== "bearer" || typeof body.scope !== "string" || !body.scope.split(/[ ,]+/).includes("gist")) return { ok: false, code: "invalid-data", message: "Invalid GitHub token response" }; if (signal.aborted || identity !== this.flow || this.now() >= deadline) return signal.aborted || identity !== this.flow ? cancelled() : expired(); const token = body.access_token; const stored = await this.queueTokenOperation(async () => { if (signal.aborted || identity !== this.flow || this.now() >= deadline) return cancelled(); const written = await this.storage.set(GITHUB_ACCESS_TOKEN_KEY, token); if (!written.ok) return written; if (signal.aborted || identity !== this.flow || this.now() >= deadline) { const removed = await this.storage.remove(GITHUB_ACCESS_TOKEN_KEY); if (!removed.ok) return removed; return signal.aborted || identity !== this.flow ? cancelled() : expired(); } return written; }); if (!stored.ok) return stored; this.revision++; await this.storage.remove(GITHUB_REVOKED_SESSION_KEY); this.setToken(token); const session = { authenticated: true as const, login: "GitHub" }; this.update(session); return { ok: true, value: session }; }
  }
  async logout(): Promise<PlatformResult<void>> { this.flow++; this.revision++; const removed = await this.queueTokenOperation(() => this.storage.remove(GITHUB_ACCESS_TOKEN_KEY)); if (removed.ok) { this.setToken(null); this.update(null); } return removed; }
  protected override async persistInvalidation(): Promise<PlatformResult<void>> { this.flow++; this.revision++; return this.queueTokenOperation(async () => { const removed = await this.storage.remove(GITHUB_ACCESS_TOKEN_KEY); if (removed.ok) { await this.storage.remove(GITHUB_REVOKED_SESSION_KEY); return removed; } const marked = await this.storage.set(GITHUB_REVOKED_SESSION_KEY, true); return marked.ok ? { ok: false, code: "authentication", message: "credential cleanup failed" } : removed; }); }
  private queueTokenOperation<T>(operation: () => Promise<PlatformResult<T>>): Promise<PlatformResult<T>> { const result = this.tokenWriteQueue.then(operation, operation); this.tokenWriteQueue = result.then(() => undefined, () => undefined); return result; }
  private async oauthRequest(url: string, body: string, signal: AbortSignal): Promise<PlatformResult<unknown>> { let response: Response; try { response = await this.fetcher(url, { method: "POST", headers: FORM_HEADERS, body, signal }); } catch (cause) { return signal.aborted ? cancelled() : { ok: false, code: "network", message: "GitHub network request failed", cause }; } if (!response.ok) return { ok: false, code: "network", message: `GitHub request failed (${response.status})` }; try { return { ok: true, value: await response.json() }; } catch (cause) { return { ok: false, code: "invalid-data", message: "GitHub returned invalid JSON", cause }; } }
}
