import type { GitHubService, GitHubSession, GistProject } from "./services";
import type { PlatformResult } from "./result";
import type { ProjectFile } from "../types";
import { clearGitHubToken, getGitHubToken } from "../utils/githubToken";
import { canonicalizeProject, GIST_API, MAX_GIST_PROJECT_BYTES, githubHeaders, gistDescription, mapGistList, pindouFiles, projectFromGist, serializeGistProject, toFilename, transportError } from "../utils/gistSync";

const TTL = 60_000;
export abstract class SessionGitHubService implements GitHubService {
  abstract readonly availability: GitHubService["availability"];
  protected session: GitHubSession | null = null;
  protected token: string | null = getGitHubToken();
  private listeners = new Set<(session: GitHubSession | null) => void>();
  private recentUploads = new Map<string, { project: GistProject; expires: number }>();
  private recentDeletes = new Map<string, number>();
  private writes = new Map<string, Promise<unknown>>();
  private credentialRevision = 0;
  constructor(protected readonly fetcher: typeof fetch = fetch, protected readonly now = Date.now) {}
  subscribe(listener: (session: GitHubSession | null) => void) { this.listeners.add(listener); return () => this.listeners.delete(listener); }
  protected update(session: GitHubSession | null) { this.session = session; this.listeners.forEach((listener) => listener(session)); }
  protected setToken(token: string | null) { if (this.token !== token) this.credentialRevision++; this.token = token; if (!token) this.clearCache(); }
  async getSession(): Promise<PlatformResult<GitHubSession | null>> { return { ok: true, value: this.session }; }
  abstract login(): Promise<PlatformResult<GitHubSession>>;
  async logout(): Promise<PlatformResult<void>> { clearGitHubToken(); this.forceInvalidate(); return { ok: true, value: undefined }; }
  protected forceInvalidate() { this.setToken(null); this.clearCache(); this.update(null); }
  protected async persistInvalidation(): Promise<PlatformResult<void>> { clearGitHubToken(); return { ok: true, value: undefined }; }
  private clearCache() { this.recentUploads.clear(); this.recentDeletes.clear(); }
  private next(link: string | null): string | null { const m = link?.match(/<([^>]+)>;\s*rel="next"/); return m?.[1]?.startsWith(`${GIST_API}/`) ? m[1] : null; }
  private async pages(url: string): Promise<PlatformResult<unknown[]>> {
    const all: unknown[] = []; let next: string | null = url;
    for (let page = 0; next && page < 20; page++) { const r = await this.requestResponse(next); if (!r.ok) return r; const data = await this.json(r.value); if (!data.ok) return data; if (!Array.isArray(data.value)) return { ok: false, code: "invalid-data" }; all.push(...data.value); next = this.next(r.value.headers.get("link")); }
    if (next) return { ok: false, code: "invalid-data", message: "Too many GitHub pages" }; return { ok: true, value: all };
  }
  async listProjects() {
    const r = await this.pages(`${GIST_API}/gists?per_page=100`); if (!r.ok) return r;
    try { const listed = mapGistList(r.value); const now = this.now(); for (const [id, x] of this.recentUploads) if (x.expires <= now) this.recentUploads.delete(id); for (const [id, x] of this.recentDeletes) if (x <= now) this.recentDeletes.delete(id); const visible = listed.filter(x => !this.recentDeletes.has(x.gistId)); for (const [id, x] of this.recentUploads) { const remote = visible.find(p => p.gistId === id); if (!remote || remote.updatedAt !== x.project.updatedAt || remote.name !== x.project.name) { if (remote) visible.splice(visible.indexOf(remote), 1); visible.unshift(x.project); } else this.recentUploads.delete(id); } return { ok: true as const, value: visible }; }
    catch (cause) { return { ok: false as const, code: "invalid-data" as const, cause }; }
  }
  private queue<T>(id: string, operation: () => Promise<T>): Promise<T> { const previous = this.writes.get(id) ?? Promise.resolve(); const result = previous.then(operation, operation); this.writes.set(id, result); void result.finally(() => { if (this.writes.get(id) === result) this.writes.delete(id); }); return result; }
  async uploadProject(name: string, project: ProjectFile, gistId?: string, expectedVersion?: string) {
    const content = serializeGistProject(project); if (new TextEncoder().encode(content).byteLength > MAX_GIST_PROJECT_BYTES) return { ok: false as const, code: "invalid-data" as const, message: "Gist project exceeds 25MB" }; if (gistId && !expectedVersion) return { ok: false as const, code: "conflict" as const, message: "Gist update requires a preflight version" };
    const execute = async () => { let oldName: string | null = null; if (gistId) { const current = await this.requestJson(`${GIST_API}/gists/${gistId}`); if (!current.ok) return current; const history = Array.isArray((current.value as any)?.history) ? (current.value as any).history : []; if (history[0]?.version !== expectedVersion) return { ok: false as const, code: "conflict" as const, message: "Remote Gist changed before upload" }; try { oldName = pindouFiles(current.value)[0][0]; } catch (cause) { return { ok: false as const, code: "invalid-data" as const, cause }; } } const filename = toFilename(name); const files: Record<string, { content: string } | null> = { [filename]: { content } }; if (oldName && oldName !== filename) files[oldName] = null; const r = await this.requestJson(gistId ? `${GIST_API}/gists/${gistId}` : `${GIST_API}/gists`, { method: gistId ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ description: gistDescription(name), ...(gistId ? {} : { public: false }), files }) }); if (!r.ok) return r; const d = r.value as any; if (!d || typeof d.id !== "string" || typeof d.updated_at !== "string") return { ok: false as const, code: "invalid-data" as const }; const latest = await this.requestJson(`${GIST_API}/gists/${d.id}`); if (!latest.ok) return latest; const verified = latest.value as any; const history = Array.isArray(verified.history) ? verified.history : []; let canonical: string; try { const downloaded = projectFromGist(verified); canonical = canonicalizeProject(downloaded.project); } catch { return { ok: false as const, code: "conflict" as const, message: "Unable to verify uploaded Gist content" }; } const version = history[0]?.version; if (typeof version !== "string" || canonical !== canonicalizeProject(project) || (gistId && history[1]?.version !== expectedVersion)) return { ok: false as const, code: "conflict" as const, message: "Intervening remote Gist revision detected" }; const value = { gistId: d.id, updatedAt: verified.updated_at, version }; this.recentDeletes.delete(d.id); this.recentUploads.set(d.id, { project: { ...value, name, description: gistDescription(name), isPublic: false }, expires: this.now() + TTL }); return { ok: true as const, value }; };
    return this.queue(gistId ?? `create:${name}`, execute);
  }
  async getProjectMetadata(gistId: string) { const response = await this.requestResponse(`${GIST_API}/gists/${gistId}`); if (!response.ok) return response; const etag = response.value.headers.get("etag") ?? undefined; const parsed = await this.json(response.value); if (!parsed.ok) return parsed; const updatedAt = (parsed.value as any)?.updated_at; const version = (parsed.value as any)?.history?.[0]?.version; return typeof updatedAt === "string" && typeof version === "string" ? { ok: true as const, value: { updatedAt, version, etag } } : { ok: false as const, code: "invalid-data" as const }; }
  async getProjectUpdatedAt(gistId: string) { const r = await this.requestJson(`${GIST_API}/gists/${gistId}`); if (!r.ok) return r; const value = (r.value as any)?.updated_at; return typeof value === "string" ? { ok: true as const, value } : { ok: false as const, code: "invalid-data" as const }; }
  async downloadProject(gistId: string, revision?: string) { const r = await this.requestJson(revision ? `${GIST_API}/gists/${gistId}/${revision}` : `${GIST_API}/gists/${gistId}`, {}, true); if (!r.ok) return r; try { const [[, file]] = pindouFiles(r.value); let content: string | undefined; if (file.truncated === true) { if (typeof file.raw_url !== "string") throw new Error("Missing raw URL"); const raw = new URL(file.raw_url); if (raw.protocol !== "https:" || raw.hostname !== "gist.githubusercontent.com") throw new Error("Unsafe raw URL"); const response = await this.rawResponse(raw.href); if (!response.ok) return response; content = await response.value.text(); if (new TextEncoder().encode(content).byteLength > MAX_GIST_PROJECT_BYTES) return { ok: false as const, code: "invalid-data" as const, message: "Gist project exceeds 25MB" }; } return { ok: true as const, value: projectFromGist(r.value, content) }; } catch (cause) { return { ok: false as const, code: "invalid-data" as const, cause }; } }
  async deleteProject(gistId: string) { return this.queue(gistId, async () => { const r = await this.requestResponse(`${GIST_API}/gists/${gistId}`, { method: "DELETE" }); if (!r.ok) return r; this.recentUploads.delete(gistId); this.recentDeletes.set(gistId, this.now() + TTL); return { ok: true as const, value: undefined }; }); }
  async listRevisions(gistId: string) { const r = await this.pages(`${GIST_API}/gists/${gistId}/commits?per_page=100`); if (!r.ok) return r; return { ok: true as const, value: r.value.map((x: any) => ({ sha: String(x.version), committedAt: String(x.committed_at) })) }; }
  private async rawResponse(url: string): Promise<PlatformResult<Response>> { const allowed = (value: string) => { try { const parsed = new URL(value); return parsed.protocol === "https:" && parsed.hostname === "gist.githubusercontent.com"; } catch { return false; } }; if (!allowed(url)) return { ok: false, code: "invalid-data", message: "Unsafe raw URL" }; let response: Response; try { response = await this.fetcher(url, { credentials: "omit" }); } catch (cause) { return { ok: false, code: "network", cause }; } if (!allowed(response.url || url)) return { ok: false, code: "invalid-data", message: "Unsafe raw redirect" }; const length = Number(response.headers.get("content-length")); if (Number.isFinite(length) && length > MAX_GIST_PROJECT_BYTES) return { ok: false, code: "invalid-data", message: "Gist project exceeds 25MB" }; if (!response.ok) return transportError(response, `GitHub raw request failed (${response.status})`, this.now()); return { ok: true, value: response }; }
  private async requestResponse(url: string, init: RequestInit = {}, size = false): Promise<PlatformResult<Response>> { if (!this.token) return { ok: false, code: "authentication", message: "GitHub login required" }; const capturedToken = this.token; const capturedRevision = this.credentialRevision; if (!url.startsWith(`${GIST_API}/`)) return { ok: false, code: "invalid-data" }; let response: Response; try { response = await this.fetcher(url, { ...init, headers: { ...githubHeaders(capturedToken), ...(init.headers ?? {}) } }); } catch (cause) { return { ok: false, code: "network", cause }; } if (response.status === 401) { if (this.token !== capturedToken || this.credentialRevision !== capturedRevision) return { ok: false, code: "authentication", message: "Stale GitHub credentials expired" }; this.forceInvalidate(); const cleared = await this.persistInvalidation(); return { ok: false, code: "authentication", message: cleared.ok ? "GitHub credentials expired" : "GitHub credentials expired; credential cleanup failed" }; } if (response.status === 412) return { ok: false, code: "conflict", message: "Remote Gist changed" }; if (!response.ok) return transportError(response, `GitHub Gist request failed (${response.status})`, this.now()); if (size && Number(response.headers.get("content-length")) > MAX_GIST_PROJECT_BYTES) return { ok: false as const, code: "invalid-data" as const, message: "Gist project exceeds 25MB" }; return { ok: true, value: response }; }
  private async json(response: Response): Promise<PlatformResult<unknown>> { if (response.status === 204) return { ok: true, value: null }; try { return { ok: true, value: await response.json() }; } catch (cause) { return { ok: false, code: "invalid-data", cause }; } }
  private async requestJson(url: string, init: RequestInit = {}, size = false) { const r = await this.requestResponse(url, init, size); return r.ok ? this.json(r.value) : r; }
}
